Repository g-sreenivasulu/portfolio, pull requests merged in 2023-07, with the labels that each got.

#88 Update Awards Page
  package-lock.json
  package.json
  public/awards/global-teacher-award/1.jpeg
  public/awards/global-teacher-award/2.jpeg
  public/awards/global-teacher-award/3.jpeg
  public/awards/yuva-aacharya-award/1.jpeg
  public/awards/yuva-aacharya-award/2.jpeg
  public/awards/yuva-aacharya-award/3.jpeg
  src/components/award-card.astro
  src/data/awards.json
  src/pages/awards.astro
  src/utils/photo-swipe.js
  src/utils/utils.ts
Labels: enhancement

#90 Move background style to global.css
  src/layouts/Layout.astro
  src/styles/global.css
Labels: refactor

#89 Add border to book card component
  src/components/book-card.astro
Labels: enhancement

#93 refactor: use compareDatesDesc function from utils
  src/pages/patents.astro
Labels: refactor

#92 Update Favicon, OG Image, SEO
  astro.config.mjs
  public/favicon.ico
  public/favicon.svg
  public/opengraph.jpg
  public/robots.txt
  src/layouts/Layout.astro
Labels: enhancement

#94 84 update footer
  src/components/footer.astro
Labels: enhancement

#96 Update dependencies
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/components/footer.astro
  src/layouts/Layout.astro
Labels: dependencies

#99 Add Color Theme
  src/components/award-card.astro
  src/components/contactform.astro
  src/components/hero.astro
  src/components/navbar/dropdown.astro
  src/components/navbar/navbar.astro
  src/components/timeline.astro
  src/components/ui/link.astro
  src/layouts/Layout.astro
  src/pages/404.astro
  src/pages/blog.astro
  src/pages/blog/[slug].astro
  src/pages/contact.astro
  src/styles/global.css
  tailwind.config.cjs
Labels: enhancement

#101 fix: add missing page description in achievements
  src/pages/achievements.astro
Labels: enhancement

#108 Clean up
  src/components/contactform.astro
  src/components/cta.astro
  src/components/features.astro
  src/components/footer.astro
  src/components/logos.astro
  src/components/pricing.astro
  src/components/ui/icons/index.js
  src/components/ui/icons/tick.astro
  src/content/config.ts
  src/content/team/janette-lynch.md
  src/content/team/marcell-ziemann.md
  src/content/team/robert-palmer.md
  src/layouts/BlogLayout.astro
  src/layouts/Layout.astro
  src/pages/about.astro
  src/pages/index.astro
  src/pages/pricing.astro
Labels: chore

#110 fix: change default author name in blog collection
  src/content/config.ts
Labels: change

#115 feat: update README.md
  README.md
Labels: enhancement

#122 Fetch profile data dynamically
  src/components/profile.astro
  src/data/profile.json
Labels: refactor

#125 Update profile and experience
  src/components/hero.astro
  src/components/profile.astro
  src/data/home.json
  src/pages/contact.astro
Labels: change

#129 fix: update number of patents
  src/data/achievements.json
Labels: change
