Repository g-sreenivasulu/portfolio, pull requests merged in 2023-04, with the labels that each got.

#41 Update professional activities page
  src/data/professional-activities.json
  src/pages/professional-activities.astro
Labels: enhancement

#49 refactor/move-profile-section-to-separate-component
  src/components/hero.astro
  src/components/profile.astro
  src/pages/index.astro
Labels: refactor

#53 Change About to Awards
  src/components/navbar/navbar.astro
  src/pages/awards.astro
Labels: change

#54 Change section heading style to semi-bold in Professional Activities Page
  src/pages/professional-activities.astro
Labels: change

#66 feat: add custom 404 page
  src/pages/404.astro
Labels: enhancement

#68 feat: add granted status
  src/components/patent-card.astro
  src/data/patents.json
  src/pages/patents.astro
Labels: enhancement
